### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by blackcatsnow** [bumbleshoot/quest-tracker#1]
I received this email from the script 

TypeError: Cannot read properties of null (reading '0')
     at updateQuestTracker (questTracker:538:95)
     at processTrigger (questTracker:222:5)
     at __GS_INTERNAL_top_function_call__.gs:1:8

**Comment by bumbleshoot** [comment]
Hi @blackcatsnow, sorry for the delay! Can you please create a new issue for this error? I just created a new issue template which will ask for all the information I need from you in order to troubleshoot. Thanks!
