### ISSUE TITLE
Blank?

### ISSUE THREAD

**Issue by HeathenKitty** [bumbleshoot/quest-tracker#3]
Per the Quest Tracker Summary, installing this will display "The spreadsheet shows how many quest completions are needed by each party member for every quest in Habitica, in order to get all the rewards. Also shows total quest completion percentages for each party member and quest." yet upon completion of all of the steps of the script, the worksheet is blank. There are no further directions stating that anything else must be completed, so I am unsure if I am missing a step to fill in the above quoted information, as it is implied that it will autofill. Please advise.

**Script version**
Quest Tracker v1.0.17

**Comment by bumbleshoot** [comment]
Hi @HeathenKitty, can you please try following the [Setup Instructions](https://github.com/bumbleshoot/quest-tracker#setup-instructions) again, very carefully, and let me know if you get the same issue? If so, I will do some more troubleshooting with you.

**Comment by HeathenKitty** [comment]
So, right off the bat, I run into a problem. I cannot move forward with
step 2 as upon completion of step 1, when it opens my google account, the
page is blank. It is not opening the quest tracker, so I cannot make a copy
of the quest tracker as described in step 2 to proceed through to step 3 &
so on. Please advise.

**Comment by bumbleshoot** [comment]
@HeathenKitty Thanks for pointing that out! Does [this link](https://script.google.com/home/projects/1l7WWIuc0V0e1He3Nr3rByrO8HqoXqUUk0HA3bi7oMyDoyLra892fo6vr/) work for you? I will update the documentation once you let me know. :)

**Comment by bumbleshoot** [comment]
Hi again @HeathenKitty, another user helped me test the link. I have updated the [Setup Instructions](https://github.com/bumbleshoot/quest-tracker#setup-instructions). Can you please try following them again?

**Comment by HeathenKitty** [comment]
They worked! Thank you so much!

**Comment by bumbleshoot** [comment]
You're welcome!
